### ISSUE TITLE
does it still work

### ISSUE THREAD

**Issue by NVParran** [Gertje823/f2f-downloader#1]
hello gertje,

i've been trying to use your script, i've been following the readme however I get the ( 'NoneType' object has no attribute 'group' )  error.
do you know if the script still works or how to fix my error?

thanks in advance!

kind regards,

NVParran

**Comment by Gertje823** [comment]
They changed some things on the site. I modified the script so it works with the recent version of the site.
I also noticed you now require a token to send the requests. For now you need to refresh the token manually. I will look if it is possible to obtain the token automatically.

**Comment by clublek** [comment]
do you have an example of working cookies.txt file and the request headers you need to put into the python script?

**Comment by Gertje823** [comment]
@clublek  Easiest way to get the headers is to open dev tools (f12) on the creators page and look for the https://f2f.com/api/creators/<username> request. right click  copy > copy as curl (bash). Go to https://curlconverter.com/ and paste it there and select Python. Now you can copy the headers to the script.

For the cookies I use a cookies to txt browser extension.

**Comment by clublek** [comment]
thanks! i'm getting the following error in the script:

Traceback (most recent call last):
  File "scraper.py", line 188, in <module>
    id = re.search('data-url=\"\/posts\/\?creator=(.*)\"', response.text).group(1)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'group'
